# Lecture 2 : Numpy Basics

# Milindi Shah
# J057

# Q1

# Matrix addition and Substraction

In [5]:
import numpy as np

In [6]:
matrix1 = np.array([[1,3],[2,4]])
matrix2 = np.array([[1,2],[3,4]])

In [7]:
print(matrix1+matrix2)

[[2 5]
 [5 8]]


#  Scalar Addition:

In [8]:
print(1+matrix1)

[[2 4]
 [3 5]]


In [9]:
print(matrix1-matrix2)

[[ 0  1]
 [-1  0]]


In [10]:
#  Scalar Substraction:

In [11]:
print(1-matrix1)

[[ 0 -2]
 [-1 -3]]


# Matrix Vector Multiplication

In [12]:
vector = np.array([9,1])
matrix = np.array([[6,2],[3,7],[1,0]])
print(np.dot(matrix,vector))

[56 34  9]


In [13]:
a = np.random.randint(low=1, high =100, size=(3,3))
b = np.random.randint(low=1, high =100, size=(3,3))

In [14]:
print('Matrix A')
print(a)
print('Matrix B')
print(b)

Matrix A
[[51 59  2]
 [61 53 37]
 [48 11 74]]
Matrix B
[[53 26 51]
 [ 7 27 67]
 [50  7 81]]


# To verify A+B = B+A

In [15]:
print(a+b)

[[104  85  53]
 [ 68  80 104]
 [ 98  18 155]]


In [16]:
print(b+a)

[[104  85  53]
 [ 68  80 104]
 [ 98  18 155]]


# To verify A.B = B.A

In [17]:
print('A.B')
print(np.dot(a,b))
print('B.A')
print(np.dot(b,a)) # Not equal

A.B
[[3216 2933 6716]
 [5454 3276 9659]
 [6321 2063 9179]]
B.A
[[6737 5066 4842]
 [5220 2581 5971]
 [6865 4212 6353]]


In [18]:
#   Therefore, A.B != B.A

# Associative Property

In [19]:
a = np.random.randint(low=1, high =100, size=(3,3))
b = np.random.randint(low=1, high =100, size=(3,3))
c = np.random.randint(low=1, high =100, size=(3,3))


In [20]:
print('(A.B).C')
print(np.dot(np.dot(a,b),c))
print('A.(B.C)')
print(np.dot(a, np.dot(b,c)))

(A.B).C
[[ 700186  736724 1468362]
 [ 455794  447406  928024]
 [ 326215  314900  658680]]
A.(B.C)
[[ 700186  736724 1468362]
 [ 455794  447406  928024]
 [ 326215  314900  658680]]


# Q3.

# Inverse Matrix


In [21]:
matrix = np.random.randint(low = 1, high =50, size=(3,3) )
print('Orignal Matrix')
print(matrix)
print('Inverse Matrix')
print(np.linalg.inv(matrix))

Orignal Matrix
[[42 38 38]
 [ 2  7 24]
 [23 17 29]]
Inverse Matrix
[[-0.03841829 -0.08545727  0.12106447]
 [ 0.09257871  0.06446777 -0.17466267]
 [-0.0238006   0.02998501  0.04085457]]


# Q4. Experimenting with Larger dimentions

In [22]:
mat1 = np.random.randint(low = 1, high =50, size=(1000,1000) )
mat2 = np.random.randint(low = 1, high =50, size=(1000,1000) )


In [23]:
print('Matrix 1')
print(mat1)
print('Matrix 2')
print(mat2)

Matrix 1
[[44 40 35 ...  7 47  9]
 [35 45 28 ... 46 12 40]
 [12  7 36 ... 20 13 23]
 ...
 [ 1 16 39 ... 37 48 37]
 [11  6 19 ...  6 47 10]
 [37 36 36 ... 31 16 37]]
Matrix 2
[[42 31 42 ... 21 46 31]
 [11 29 23 ... 21  9 32]
 [43 35 30 ... 17 36  1]
 ...
 [38 13 37 ... 27 13 46]
 [ 9 33 25 ...  9 14 36]
 [21 11 13 ... 12 21 36]]


In [24]:
m = mat1.shape[0]
p = mat2.shape[0]

In [25]:
assert mat1.shape == mat2.shape

In [26]:
import time 

In [27]:
r,c = mat1.shape
final = []
start = time.time()
for i in range(r):
    
    for j in range(c):
        row = mat1[i,j]+mat2[i,j]
    final.append(row)
    
print(time.time()-start)

1.2021324634552002


## Through Numpy:

In [28]:
start = time.time()
np_ans = mat1+mat2
print(time.time()-start)

0.002986907958984375


In [29]:
# Therefore, numpy Addition is a lot faster

# Matrix Multiplication

In [30]:
assert mat1.shape[0] == mat2.shape[1]

In [37]:
start = time.time()
m = mat1.shape[0]
p = mat2.shape[1]
n = mat2.shape[0]

In [38]:
answer = np.zeros((m,p))

In [39]:
mat1 = np.random.randint(low = 1, high =50, size=(100,100) )
mat2 = np.random.randint(low = 1, high =50, size=(100,100) )


In [40]:
m = mat1.shape[0]
n = mat2.shape[0]
c =mat2.shape[1]
for i in range(m):
    for j in range(c):
        for k in range(n):
            answer[i,j] += mat1[i,k] * mat2[k,j]
print(time.time()-start)           

3.255744218826294


# Through Numpy:

In [41]:
start = time.time()
np_dotProduct_result = np.dot(mat1, mat2)
print(time.time()-start)

0.0


In [43]:
# Therefore, numpy Addition is a lot faster